/**
 * @fileoverview Font Awesome library configuration.
 *
 * Registers all brand and solid icons used across the site into the FA library.
 * Import this file once in layout.js — it replaces the render-blocking CDN
 * <link> tag with tree-shakeable, self-hosted SVG icons.
 *
 * To add a new icon: import it from the appropriate package and add it to
 * the library.add() call below.
 */

import { library, config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

// Prevent FA from injecting its own <style> tag (we import the CSS above)
config.autoAddCss = false;

// ── Brand icons (fab) ────────────────────────────────────────────────────────
import {
  faDribbble,
  faBehance,
  faInstagram,
  faLinkedin,
  faGithub,
  faFigma,
  faTwitter,
} from '@fortawesome/free-brands-svg-icons';

// ── Solid icons (fas) ────────────────────────────────────────────────────────
import {
  faArrowRight,
  faSearch,
  faImage,
  faLink,
  faExternalLinkAlt,
  faShoppingCart,
  faCheckCircle,
  faGlobe,
  faNewspaper,
  faPlus,
  faTrash,
  faTrashAlt,
  faTimes,
  faSave,
  faSpinner,
  faExclamationTriangle,
  faKey,
  faSyncAlt,
  faCloudUploadAlt,
  faCheck,
  faSort,
  faFilter,
  faBold,
  faItalic,
  faStrikethrough,
  faCode,
  faListUl,
  faListOl,
  faQuoteRight,
  faMinus,
  faUndo,
  faRedo,
  faEye,
  faEdit,
  faCog,
  faLayerGroup,
  faPaperclip,
  faExpandAlt,
  faCompressAlt,
  faDownload,
  faStar,
  faCopy,
  faInfoCircle,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faUser,
  faEnvelope,
  faLock,
  faSignOutAlt,
  faHome,
  faBlog,
  faBriefcase,
  faAddressCard,
  faDatabase,
  faServer,
  faRocket,
  faTags,
  faTrophy,
  faCertificate,
  faPenAlt,
  faCamera,
  faVideo,
  faPalette,
  faMobile,
  faDesktop,
  faTablet,
  faWrench,
  faBolt,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  // Brand
  faDribbble,
  faBehance,
  faInstagram,
  faLinkedin,
  faGithub,
  faFigma,
  faTwitter,
  // Solid
  faArrowRight,
  faSearch,
  faImage,
  faLink,
  faExternalLinkAlt,
  faShoppingCart,
  faCheckCircle,
  faGlobe,
  faNewspaper,
  faPlus,
  faTrash,
  faTrashAlt,
  faTimes,
  faSave,
  faSpinner,
  faExclamationTriangle,
  faKey,
  faSyncAlt,
  faCloudUploadAlt,
  faCheck,
  faSort,
  faFilter,
  faBold,
  faItalic,
  faStrikethrough,
  faCode,
  faListUl,
  faListOl,
  faQuoteRight,
  faMinus,
  faUndo,
  faRedo,
  faEye,
  faEdit,
  faCog,
  faLayerGroup,
  faPaperclip,
  faExpandAlt,
  faCompressAlt,
  faDownload,
  faStar,
  faCopy,
  faInfoCircle,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faUser,
  faEnvelope,
  faLock,
  faSignOutAlt,
  faHome,
  faBlog,
  faBriefcase,
  faAddressCard,
  faDatabase,
  faServer,
  faRocket,
  faTags,
  faTrophy,
  faCertificate,
  faPenAlt,
  faCamera,
  faVideo,
  faPalette,
  faMobile,
  faDesktop,
  faTablet,
  faWrench,
  faBolt
);
